"""
Django settings for super5 project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

os.environ["LANG"] = "en_US.UTF-8"
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'gn4qtq0(@+7g$sl4y^enz-oyyehl@rpqqoc(e7p451=^tg&kjn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = (
    'super_inlines',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'formtools',
    'social.apps.django_app.default',
    'oauth2_provider',
    'redactor',
    'blogs',
    'super5',
    'rest_framework',
    'accounts',
    'athletes',
    'faq',
    'logs',
    'extend_notifications',
    'trainings',
    'pinax.notifications',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',

    'logs.middleware.LoggingMiddleware',
)

ROOT_URLCONF = 'super5.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['%s/templates' % BASE_DIR, '%s/templates/errors' % BASE_DIR, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
            ],
        },
    },
]

AUTH_USER_MODEL = 'accounts.FiveUser'

AUTHENTICATION_BACKENDS = (
    'social.backends.vk.VKOAuth2',
    'social.backends.facebook.FacebookOAuth2',
    'social.backends.google.GoogleOAuth2',
    'social.backends.odnoklassniki.OdnoklassnikiOAuth2',
    'social.backends.mailru.MailruOAuth2',
    'social.backends.yandex.YandexOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_VK_OAUTH2_KEY = '4907782'
SOCIAL_AUTH_VK_OAUTH2_SECRET = 'S72red5P1Te45XKSQMf4'

SOCIAL_AUTH_FACEBOOK_KEY = '285082911662001'
SOCIAL_AUTH_FACEBOOK_SECRET = 'cfd45634195a084974fc0405d59ae71a'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '1061731545169-ruh9nt7fvrs24oqaecvl15u4c7gi0e1m@developer.gserviceaccount.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'tF1hCzU0OQrygk5QRDUs96cK'

SOCIAL_AUTH_ODNOKLASSNIKI_OAUTH2_KEY = '1137740544'
SOCIAL_AUTH_ODNOKLASSNIKI_OAUTH2_SECRET = '5AAC02ADE544906F7BBEA10B'
SOCIAL_AUTH_ODNOKLASSNIKI_OAUTH2_PUBLIC_NAME = 'CBAMIBNEEBABABABA'

SOCIAL_AUTH_MAILRU_OAUTH2_KEY = '733867'
SOCIAL_AUTH_MAILRU_OAUTH2_SECRET = '2270661db2f46fb3c3985a51e0fa66ff'

SOCIAL_AUTH_YANDEX_OAUTH2_KEY = '1ade8d0ca0d44ed7a958fa66f34634d4'
SOCIAL_AUTH_YANDEX_OAUTH2_SECRET = '4e3a04a796a945fbb2c3c4c181dc771e'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/accounts/personal-data'
SOCIAL_AUTH_LOGIN_URL = '/'

WSGI_APPLICATION = 'super5.wsgi.application'

OAUTH2_PROVIDER = {
    'SCOPES': {
        'read': 'Read scope',
        'write': 'Write scope'
    },
    'ACCESS_TOKEN_EXPIRE_SECONDS': 100000,
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static/'),
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

REDACTOR_OPTIONS = {'lang': 'ru', }
REDACTOR_UPLOAD = '/media/user_uploads/'
REDACTOR_UPLOAD_HANDLER = 'utils.classes.CustomHandler'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'sitesuper5project@gmail.com'
EMAIL_HOST_PASSWORD = 'super5-password'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.ext.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework.filters.DjangoFilterBackend',
    ),
}

REST_SESSION_LOGIN = False

DEFAULT_FROM_EMAIL = 'sitesuper5project@gmail.com'

PINAX_NOTIFICATIONS_BACKENDS = (
    ("email", "extend_notifications.backends.email.ExtendEmailBackend"),
    ("rest", "extend_notifications.backends.rest.RestBackend"),
)

TRAINING_SERVICE_URL = 'http://super5-program-resolver.huskyjam.com/jsonrpc'

TRAINING_SERVICE_SECRET_KEY = \
    'akjhdsfgaliweuj7fkhgLHZSDOIuyg3wteja5reshjkruyf3tyjkquwLJRYHFGZDJYGKF4532EWHGGASSFHLK23JDFHGALS0987DFJDSAF'

SITE_ID = 1
